#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
	      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi
