format = """
[](238)\
$time\
[](bg:240 fg:238)\
$username\
[](bg:238 fg:240)\
$hostname\
[](bg:31 fg:238)\
$directory\
[](fg:31 bg:148)\
$git_branch\
[](fg:148 bg:128)\
$git_status\
$git_state\
[](fg:128 bg:89)\
$python\
$golang\
$gradle\
$java\
$nodejs\
$rust\
[ ](fg:89 bg:214)\
$status\
[ ](fg:214)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

[hostname]
ssh_only = false
style = "bg:238 fg:250"
format = '[ $hostname ]($style)'
disabled = false

[status]
disabled = false
style = "bg:214 fg:18"
success_symbol = "y"
format = "[$int ]($style)"

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:240 fg:250"
style_root = "bg:124"
format = '[ $user ]($style)'
disabled = false


[directory]
style = "bg:31 fg:250"
read_only = "  "
read_only_style = "fg:250 bg:124"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
disabled = true

[docker_context]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[git_branch]
symbol = ""
style = "bg:148 fg:0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:128 fg:255"
format = '[ $all_status$ahead_behind ]($style)'

[git_state]
style = "bg:128 fg:255"
format = '[ $state( $progress_current/$progress_total) ]($style)'

[golang]
symbol = " "
style = "bg:89 fg:248"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:89 fg:250"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:89 fg:250"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:89 fg:248"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:89 fg:250"
format = '[ $symbol ($version) ]($style)'

[scala]
enabled = false

[time]
disabled = false
time_format = "%T" # Hour:Minute Format
style = "bg:238 fg:250"
format = '[ $time ]($style)'

[python]
style = "bg:89 fg:248"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
